module.exports = [
    "Walk or bike for short trips instead of driving to reduce carbon emissions and promote physical activity.",
    "Use public transportation such as buses, trains, or subways for commuting or traveling longer distances.",
    "Carpool with coworkers, friends, or neighbors to share rides and reduce the number of vehicles on the road.",
    "Choose electric or hybrid vehicles for lower emissions and reduced reliance on fossil fuels.",
    "Plan errands and trips efficiently to minimize driving time and distance traveled.",
    "Investigate alternative transportation options like car-sharing services or bike rentals for occasional use.",
    "Practice eco-driving techniques such as gentle acceleration, maintaining a steady speed, and avoiding unnecessary idling to improve fuel efficiency.",
    "Support initiatives to improve walking and biking infrastructure in your community, such as bike lanes and pedestrian-friendly streets.",
    "Telecommute or work from home when possible to reduce the need for daily commuting.",
    "Combine multiple errands into one trip to minimize vehicle usage and fuel consumption.",
    "Consider downsizing to a smaller, more fuel-efficient vehicle if feasible.",
    "Plan vacations and travel itineraries that prioritize sustainable transportation options such as trains or buses.",
    "Advocate for public policies and investments that support sustainable transportation infrastructure and initiatives.",
    "Use ride-sharing apps or services to share rides with others heading in the same direction.",
    "Encourage your workplace to provide incentives for employees to use alternative transportation options.",
    "Calculate and offset your carbon footprint from transportation by supporting carbon offset projects or initiatives.",
    "Practice defensive driving techniques to reduce fuel consumption and minimize emissions.",
    "Choose walking or cycling for leisure activities and exercise instead of driving to gym or fitness centers.",
    "Support the development of renewable energy infrastructure for electric vehicles by advocating for clean energy policies.",
    "Use online tools and apps to plan routes and find alternative transportation options for your daily commute.",
    "Participate in community bike-sharing programs or initiatives to promote cycling as a sustainable transportation option.",
    "Explore options for telecommuting, flexible work schedules, or remote meetings to reduce the need for frequent travel.",
    "Advocate for improved access to public transportation in your community, including expanded routes and increased frequency.",
    "Educate yourself about the environmental impact of different transportation modes and make informed choices when traveling.",
    "Join or support local advocacy groups and organizations that promote sustainable transportation solutions in your area."
];