module.exports = [
    "Upgrade to energy-efficient appliances with high Energy Star ratings to reduce electricity consumption.",
    "Seal drafts around windows and doors with weatherstripping or caulking to prevent heat loss during colder months.",
    "Install a programmable thermostat to automatically adjust temperatures based on your schedule and save energy when heating or cooling is not needed.",
    "Use ceiling fans to improve air circulation and reduce the need for air conditioning in warmer months. Remember to turn them off when not in use.",
    "Switch to LED or CFL light bulbs, which use less energy and last longer than traditional incandescent bulbs.",
    "Unplug electronics and appliances when not in use to prevent phantom energy consumption from standby power.",
    "Insulate your home properly, including walls, floors, and attics, to retain heat in winter and keep cool air in during summer.",
    "Take shorter showers and use low-flow showerheads to reduce hot water usage and energy required for heating.",
    "Wash clothes in cold water whenever possible to save energy used for heating water. Hang clothes to dry or use a clothesline instead of a dryer.",
    "Close curtains or blinds at night to retain heat during colder months and keep rooms cooler during warmer months.",
    "Keep air vents clear of furniture and other obstructions to ensure efficient airflow from heating and cooling systems.",
    "Use natural ventilation by opening windows and doors strategically to let in cool air during breezy days or evenings.",
    "Cook efficiently by using lids on pots and pans, matching cookware size to burner size, and using microwave or toaster oven for small meals.",
    "Set your water heater temperature to 120°F (49°C) to save energy and prevent scalding.",
    "Plant shade trees around your home to block sunlight and reduce cooling needs in warmer months.",
    "Invest in energy-efficient windows with low-emissivity coatings and insulated frames to reduce heat transfer and improve insulation.",
    "Consider installing solar panels or solar water heaters to generate clean, renewable energy and reduce reliance on grid electricity.",
    "Schedule regular maintenance for HVAC systems to ensure they operate efficiently and replace air filters as recommended.",
    "Reduce heat loss from your fireplace by installing a tightly fitting fireplace insert or glass doors and closing the damper when not in use.",
    "Use a power strip to easily turn off multiple electronics and appliances at once to avoid standby power consumption.",
    "Opt for natural lighting during the day by opening curtains and blinds to reduce the need for artificial lighting.",
    "Invest in energy-saving window treatments like honeycomb shades or thermal curtains to improve insulation and reduce heat gain or loss.",
    "Upgrade to energy-efficient water heaters, such as heat pump water heaters or tankless models, to save energy and reduce utility costs.",
    "Consider upgrading to energy-efficient HVAC systems, including high-efficiency furnaces, air conditioners, and heat pumps, for long-term energy savings.",
    "Educate yourself and your family members about energy-saving habits and encourage everyone to be mindful of energy use in daily activities."
];