module.exports = [
    "Reduce meat consumption by incorporating more plant-based meals into your diet.",
    "Eat locally sourced and seasonal foods to reduce the environmental impact of transportation and support local farmers.",
    "Minimize food waste by planning meals, storing food properly, and using leftovers creatively.",
    "Support sustainable seafood options by choosing seafood certified by organizations like the Marine Stewardship Council.",
    "Grow your own fruits, vegetables, and herbs at home, either in a garden plot or container garden.",
    "Choose organic produce whenever possible to reduce exposure to pesticides and support environmentally friendly farming practices.",
    "Participate in community-supported agriculture (CSA) programs to receive fresh, locally grown produce directly from farmers.",
    "Conserve water by soaking grains and legumes before cooking instead of letting the tap run.",
    "Shop at farmers' markets or join a food co-op to access fresh, locally produced foods.",
    "Learn about the environmental impact of different food choices and make informed decisions about what you eat.",
    "Reduce consumption of processed and packaged foods, which often have a higher carbon footprint.",
    "Support restaurants and food establishments that prioritize sustainable sourcing and environmentally friendly practices.",
    "Experiment with plant-based protein sources like beans, lentils, tofu, and tempeh as alternatives to meat.",
    "Read labels and choose products with minimal packaging or eco-friendly packaging materials.",
    "Educate yourself about sustainable agriculture and food systems to advocate for positive change in your community.",
    "Cook meals from scratch using whole, unprocessed ingredients to minimize packaging waste and reduce reliance on convenience foods.",
    "Start a home garden to grow fresh produce and herbs, even if you have limited space.",
    "Reduce portion sizes and avoid overeating to minimize food waste and promote mindful eating habits.",
    "Support sustainable farming practices by purchasing products with certifications like USDA Organic or Fair Trade.",
    "Plan meals ahead of time and create shopping lists to avoid impulse purchases and reduce food waste.",
    "Share meals with family and friends to foster community connections and reduce individual food waste.",
    "Choose plant-based milk alternatives like almond milk, soy milk, or oat milk instead of dairy milk to reduce environmental impact.",
    "Compost food scraps and organic waste to divert them from landfills and create nutrient-rich soil for gardening.",
    "Advocate for policies that promote sustainable agriculture, protect natural resources, and support local food systems.",
    "Consider the carbon footprint of different foods and prioritize options with lower environmental impact when making dietary choices."
];