module.exports = [
    "Buy second-hand or refurbished goods whenever possible to extend the lifespan of products and reduce waste.",
    "Support ethical and eco-conscious brands that prioritize sustainability and environmental responsibility.",
    "Reduce overall consumption by practicing mindful purchasing habits and avoiding unnecessary or impulse buys.",
    "Repair and maintain items instead of replacing them whenever feasible.",
    "Shop locally to support small businesses and reduce the environmental impact of transportation.",
    "Choose products made from sustainable materials such as organic cotton, bamboo, or recycled materials.",
    "Avoid single-use items and opt for reusable alternatives, such as cloth shopping bags and stainless steel water bottles.",
    "Research companies and products to ensure they align with your values and environmental standards.",
    "Opt for minimalist and zero-waste lifestyles by reducing clutter and simplifying your possessions.",
    "Bring your own containers or bags when shopping for bulk items to reduce packaging waste.",
    "Support fair trade products that ensure fair wages and working conditions for producers and workers.",
    "Reduce packaging waste by buying in bulk or choosing products with minimal or recyclable packaging.",
    "Shop at farmers' markets, community-supported agriculture (CSA) programs, and local artisans for fresh, locally produced goods.",
    "Avoid fast fashion and trend-driven clothing brands in favor of timeless, high-quality garments that last longer.",
    "Consider the lifecycle of products before purchasing, including manufacturing, transportation, use, and disposal.",
    "Educate yourself about greenwashing and deceptive marketing practices to make informed purchasing decisions.",
    "Support businesses and brands that prioritize sustainability throughout their supply chain, from sourcing to production to distribution.",
    "Invest in durable, high-quality products that are designed to last and can be repaired or upgraded over time.",
    "Shop for eco-friendly alternatives to common household products, such as biodegradable cleaning supplies and compostable kitchen items.",
    "Participate in clothing swaps, thrift shopping, and clothing rental services to reduce the environmental impact of fashion consumption.",
    "Explore DIY and upcycling projects to repurpose old or discarded items into new creations.",
    "Support local artisans and craftspeople by purchasing handmade goods and unique artisanal products.",
    "Reduce reliance on single-use plastics by choosing reusable alternatives, such as stainless steel straws and silicone food storage bags.",
    "Advocate for policies and regulations that promote sustainability and responsible consumption practices at the local, national, and global levels."
];