module.exports = [
    "Start a compost bin for fruit and vegetable scraps, coffee grounds, and eggshells.",
    "Carry reusable bags when grocery shopping to avoid single-use plastic bags.",
    "Invest in a durable, reusable water bottle made from stainless steel or glass.",
    "Skip the plastic straw or opt for reusable alternatives made from materials like stainless steel, bamboo, or silicone.",
    "Pack lunches and leftovers in reusable containers instead of disposable plastic bags or wraps.",
    "Purchase items like grains, nuts, and spices from bulk bins using reusable containers to minimize packaging waste.",
    "Plan meals, use up leftovers creatively, and store food properly to minimize food spoilage and waste.",
    "Use a reusable coffee cup or travel mug when getting coffee to-go to avoid disposable cups.",
    "Carry reusable utensils made from bamboo, stainless steel, or other eco-friendly materials for meals on-the-go.",
    "Choose household cleaning and personal care products that offer refill options to reduce packaging waste.",
    "Switch from paper napkins to cloth napkins for meals to reduce paper waste.",
    "Reuse glass jars from food products for storing leftovers, organizing items, or making homemade jams and pickles.",
    "Instead of throwing away items you no longer need, donate them to charity or sell them online to give them a second life.",
    "Fix broken items like clothing, electronics, and furniture instead of discarding them and buying new ones.",
    "Opt out of receiving unsolicited mail and catalogs to reduce paper waste. Use online services to unsubscribe from mailing lists.",
    "Explore thrift stores, consignment shops, and online marketplaces for gently used clothing, furniture, and household items.",
    "Shred paper documents and non-glossy paper and add them to your compost pile to reduce paper waste.",
    "Look for products with minimal or recyclable packaging to reduce waste generated from packaging materials.",
    "Create homemade cleaning solutions using ingredients like vinegar, baking soda, and essential oils to reduce reliance on commercial cleaners in plastic bottles.",
    "Learn basic sewing skills to mend clothing, sew on buttons, and repair minor tears instead of discarding garments prematurely.",
    "Reuse envelopes from mail for jotting down notes, making shopping lists, or organizing receipts.",
    "Choose well-made, durable products that will last longer and withstand wear and tear, reducing the need for frequent replacements.",
    "Organize a clothing swap with friends or neighbors to exchange clothing and accessories, giving items a new home and reducing clothing waste.",
    "Consider using cloth diapers instead of disposable diapers for babies to reduce the amount of waste generated from diapering.",
    "Share your knowledge and enthusiasm for waste reduction with friends, family, and community members to inspire others to adopt sustainable habits."
];