module.exports = [
    "Fix leaks promptly to prevent water wastage and save on your water bill.",
    "Take shorter showers to reduce water usage, or consider installing a water-saving showerhead.",
    "Upgrade to water-saving appliances such as low-flow toilets, faucet aerators, and high-efficiency washing machines.",
    "Collect rainwater in barrels or containers to use for watering plants and gardens, reducing the need for tap water.",
    "Turn off the tap while brushing teeth or washing dishes to conserve water.",
    "Water outdoor plants in the early morning or late evening to minimize evaporation.",
    "Sweep driveways and sidewalks instead of using a hose for cleaning.",
    "Install a drip irrigation system for gardens and landscapes to deliver water directly to plant roots, minimizing runoff and evaporation.",
    "Mulch garden beds to retain soil moisture and reduce the frequency of watering.",
    "Reuse water from activities like rinsing fruits and vegetables or boiling pasta for watering indoor or outdoor plants.",
    "Consider replacing lawn grass with drought-tolerant plants or native landscaping that requires less water.",
    "Use a broom instead of a hose to clean outdoor surfaces like decks and patios.",
    "Monitor your water usage with a water meter and set goals for reducing consumption.",
    "Install a rain sensor on irrigation systems to prevent watering during rainy periods.",
    "Consider installing a greywater recycling system to reuse water from showers, sinks, and laundry for irrigation purposes.",
    "Fix dripping faucets and running toilets promptly to prevent water waste.",
    "Choose plants that are native to your region and require less water to thrive in your garden.",
    "Cover swimming pools when not in use to reduce evaporation and water loss.",
    "Use a bucket or watering can instead of a hose when watering plants to target specific areas and avoid overwatering.",
    "Inspect and maintain irrigation systems regularly to ensure efficient water distribution and minimize leaks.",
    "Teach children and family members about the importance of water conservation and encourage them to adopt water-saving habits.",
    "Use a broom or rake instead of a hose to clean outdoor surfaces like driveways and sidewalks.",
    "Install aerators on faucets to reduce water flow without compromising water pressure.",
    "Choose water-efficient landscaping options such as xeriscaping or native plant gardens.",
    "Refrain from washing vehicles frequently and use a commercial car wash that recycles water whenever possible."
];